WIP: Update to latest vuetify
kitware-data-solutions/miqa-phase1 pull request #21
Opened 2020-08-04 03:03 UTC by scottwittenburg

Tried to exercise most of the app that is enabled for me to root out any issues with the migration.  There is still at least one (perhaps more) issue remaining:

- [ ] Fix problems with keyboard shortcuts dialog
- [ ] Fix deprecation warning and lock icon alignment in girder user modal dialog
- [ ] Fix alignment of window/level sliders with numeric inputs

2020-08-05 02:47 UTC, scottwittenburg commented
I'm not sure what we need to do to move forward to the most recent release of the @babel packages I pinned in [0ea1621](https://github.com/OpenImaging/miqa/pull/21/commits/0ea1621c7ac4662c76fa26021e21bd2fa1f4afab).  But with [7.11.1](https://github.com/babel/babel/releases/tag/v7.11.1), I started getting compilation failures like:

```
 ERROR  Failed to compile with 5 errors                                                                                                                                                                                              6:44:47 PM

 error  in ./node_modules/@girder/components/src/components/Breadcrumb.vue?vue&type=script&lang=js&

Syntax Error: SyntaxError: /Users/scott/projects/miqa/miqa/client/node_modules/@girder/components/src/components/Breadcrumb.vue: Unexpected token (40:15)

  38 |     pathBreadcrumb: {
  39 |       default: [],
> 40 |       async get() {
     |                ^
  41 |         this.loading = true;
  42 |         const breadcrumb = [];
  43 |         const { rootLocationDisabled, girderRest, location } = this;


 @ ./node_modules/@girder/components/src/components/Breadcrumb.vue?vue&type=script&lang=js& 1:0-251 1:267-270 1:272-520 1:272-520
 @ ./node_modules/@girder/components/src/components/Breadcrumb.vue
 @ ./node_modules/@girder/components/src/components/index.js
 @ ./node_modules/@girder/components/src/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

Sticking with the previous release version, `7.11.0` works around the problem for the time being.

2020-08-05 02:58 UTC, scottwittenburg commented
fyi @aashish24

2020-08-05 14:16 UTC, aashish24 commented
@scottwittenburg I am thinking if we can have someone perhaps @jourdain brandon davis or @bryonlewis review our work in MIQA.

2020-08-11 18:40 UTC, scottwittenburg commented on client/src/components/KeyboardShortcutDialog.vue
> +          <template v-slot:body="{ items }">
Try to use item slot rather than body slot

2020-08-11 18:42 UTC, scottwittenburg commented on client/src/components/KeyboardShortcutDialog.vue
> +                <td v-html="item[1]"></td>
Factor out so we don't have the repeated `<code></code>` text in the data above.

2020-08-11 18:47 UTC, scottwittenburg commented on client/src/components/KeyboardShortcutDialog.vue
> +              <tr v-for="item in items" :key="item[0]">
Use the index for the key `for (item,i)` instead of the name, which should be safe since this is a static list.  Not relevant if we use the item slot instead of body.

2020-08-20 15:45 UTC, scottwittenburg commented
Just curious if you think you'll have a chance to look at this @BryonLewis?

2020-08-20 16:40 UTC, BryonLewis commented
I should be able to take a look at it tomorrow afternoon.  Could you assign me as a reviewer?

2020-08-20 16:45 UTC, scottwittenburg commented
> I should be able to take a look at it tomorrow afternoon. Could you assign me as a reviewer?

Thanks!  Although I typed your github username in as a reviewer, it insists there is "nothing to show", and the list of reviewers remains unchanged.  I'll keep trying.

2020-08-20 17:06 UTC, jourdain commented
That means you need to add him to the project before you can add him as a reviewer.

2020-08-21 12:24 UTC, BryonLewis requested changes
I took a brief look at what was changed and tried my best to verify stuff in the interface when compared with master.  Not understanding the entire use-case or workflow of the project I just looked at code changes and tried to investigate to make sure they reflected the proper actions. 

I took a short look at the Babel upgrade thing and you might have a better understanding than me.  What I can see is it gets tripped up on this custom plugin used in GirderWebComponents to create asynchronous computed properties.  It may be a breaking change that was created on babel, or perhaps that plugin was exploiting something unknown.  It would be something to watch out for on GWC when a new stable release of babel comes out.

2020-08-21 12:24 UTC, BryonLewis commented on client/src/components/CSVConfig.vue
> +          autocomplete="on"
While it's fine to leave this in here, I think vuetify has the browser version of autocomplete on most text fields by default.  I think you only need to add this if it you want to disable it or turn it to 'off', although there is a bigger discussion with how Chrome at one point just defaulted to all fields having it on.  Again it doesn't hurt anything to leave it in here so you can dismiss this comment.

2020-08-21 12:24 UTC, BryonLewis commented on client/src/components/SiteConfig.vue
> +    hide-default-filter
will double check, but do you mean to have `hide-default-footer` here.  The previous command would hide the the controls including pagination, not finding the `hide-default-filter` in the docs for `v-data-table`

2020-08-21 12:24 UTC, BryonLewis commented on client/src/views/Dataset.vue
> +                  </template>
Vuetify tooltip structure is incredibly annoying.  I think what you want is below:
```
<v-tooltip top>
                    <template v-slot:activator="{ on }">
                      <v-btn
                        text
                        icon
                        small
                        color="grey"
                        class="my-0"
                        v-on="on"
                        @click="loadSessionMeta"
                      >
                        <v-icon>undo</v-icon>
                      </v-btn>
                    </template>
                    <span>Revert</span>
                  </v-tooltip>
```

2020-08-24 17:14 UTC, scottwittenburg commented on client/src/components/CSVConfig.vue
> +          autocomplete="on"
Thanks for providing some useful background info on this, I'll just resolve for now.

2020-08-24 17:19 UTC, scottwittenburg commented on client/src/components/SiteConfig.vue
> +    hide-default-filter
Yep, good catch, thanks.  According to the [migration guide](https://vuetifyjs.com/en/getting-started/releases-and-migrations/#releases-and-migrations), `hide-actions` has been renamed to `hide-default-footer`, not `hide-default-filter`.  I just mistyped that somehow, can't even blame sublime for auto-completing incorrectly in this case.

2020-08-24 20:32 UTC, scottwittenburg commented on client/src/views/Dataset.vue
> +                  </template>
Yes, with your suggested change, I could see that button and tooltip, once I found data that passed the condition for rendering it.  Thanks!

2020-08-28 22:17 UTC, scottwittenburg commented
Thanks for reviewing this @BryonLewis 😃 I think I addressed your concerns, can you take another look when you get a chance, and approve if it looks ok to you?

2020-08-31 12:03 UTC, BryonLewis approved these changes
Looks good based on the code changes.  Just a reminder that I'm not familiar with the scope of the program and what it is supposed to do so I don't know about any overall integration changes that could of broken something outside of the code you changed.

2020-08-31 16:40 UTC, scottwittenburg commented
> Looks good based on the code changes.

I think that's all we can really ask of you, thanks for taking the time to have a look and provide some feedback!

2020-08-31 16:40 UTC, merged