Perf itkjs workerpool
kitware-data-solutions/miqa-phase1 pull request #39
Opened 2020-12-07 18:05 UTC by scottwittenburg

2020-12-07 19:38 UTC, dzenanz commented
This dragged in all the commits from #35, because it has not been merged yet.

2020-12-07 20:03 UTC, scottwittenburg commented
Yes, thanks @dzenanz, if this becomes good enough to consider truly adding, I'll either tack it on to the end of that PR, or else rebase this on master (after that's merged).

2020-12-07 20:22 UTC, dzenanz commented
Time to rebase :D

2021-02-10 03:40 UTC, scottwittenburg commented
This will need the cancel api addition to the `WorkerPool` in this [PR](https://github.com/InsightSoftwareConsortium/itk-js/pull/395) to `itk.js` when it is merged and released.

2021-02-24 19:42 UTC, scottwittenburg commented on client/src/components/JSONConfig.vue
> +              'Needs to be a json file'
I thought I had replaced this with "Needs to be a json or csv file", but I must have missed it.  I'll fix it before we merge.

2021-02-24 19:50 UTC, dzenanz approved these changes
Code looks good after a short look.

2021-02-25 17:40 UTC, thewtex approved these changes

2021-02-25 19:55 UTC, aashish24 commented
itk-js + miqa = 

![image](https://user-images.githubusercontent.com/146527/109209345-6db10d00-7779-11eb-8d4a-ec291c614e51.png)

2021-03-11 08:59 UTC, jimklo requested changes
See comments.

2021-03-11 08:59 UTC, jimklo commented on devops/docker/Dockerfile
> +RUN wget https://bootstrap.pypa.io/3.5/get-pip.py && python3 get-pip.py
This URL causes an error on build.

Should be `https://bootstrap.pypa.io/pip/3.5/get-pip.py` instead.

2021-03-22 16:44 UTC, scottwittenburg commented
@jeffbaumes This is the PR I was just mentioning

2021-04-05 15:39 UTC, merged